/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.32
 * Generated at: 2019-09-04 15:30:17 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.hcl.CollegeProject.FeedbackCrud;
import com.hcl.CollegeProject.FeedBack;
import org.hibernate.Transaction;
import org.hibernate.Session;
import com.hcl.CollegeProject.HibernateUtil;
import org.hibernate.SessionFactory;

public final class FeedBackConfirm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("org.hibernate.Transaction");
    _jspx_imports_classes.add("com.hcl.CollegeProject.HibernateUtil");
    _jspx_imports_classes.add("com.hcl.CollegeProject.FeedBack");
    _jspx_imports_classes.add("org.hibernate.SessionFactory");
    _jspx_imports_classes.add("org.hibernate.Session");
    _jspx_imports_classes.add("com.hcl.CollegeProject.FeedbackCrud");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");

  String fid=(String)session.getAttribute("fid");
  String name=(String)session.getAttribute("name");
  String inst=(String)session.getAttribute("inst");
  String sub=request.getParameter("subject");
  String fidv=request.getParameter("feedback");

      out.write("\r\n");
      out.write("\r\n");
      out.write("<form action=\"FeedBackConfirm.jsp\" method=\"get\">\r\n");
      out.write("<center>\r\n");
      out.write("Feedback Id:<input type=\"text\" name=\"feedbackId\" value=");
      out.print(fid );
      out.write(" /><br/><br/>\r\n");
      out.write("Student Name:<input type=\"text\" name=\"StudentName\" value=");
      out.print(name );
      out.write(" /><br/><br/>\r\n");
      out.write("Instructor Name:<input type=\"text\" name=\"Instructor\" value=");
      out.print(inst );
      out.write(" /> <br/><br/>\r\n");
      out.write("Subject:<input type=\"text\" name=\"Subject\" value=");
      out.print(sub );
      out.write(" /> <br/><br/>\r\n");
      out.write("FeedBack:<input type=\"text\" name=\"feedbackvalue\" value=");
      out.print(fidv );
      out.write(" /> <br/><br/>\r\n");
      out.write("         <input type=\"submit\" value=\"Confirm Feedback\" />\r\n");
      out.write("</center>\r\n");
      out.write("</form>\r\n");

if(request.getParameter("feedbackId")!=null &&
    request.getParameter("StudentName")!=null &&
    request.getParameter("Instructor")!=null &&
    request.getParameter("Subject")!=null &&
    request.getParameter("feedbackvalue")!=null){
	SessionFactory sf=HibernateUtil.getConnection();
	Session s=sf.openSession();
	FeedBack f=new FeedBack();
	f.setStudentName(request.getParameter("StudentName"));
	f.setFbvalue(request.getParameter("feedbackvalue"));
	f.setFid(request.getParameter("feedbackId"));
	f.setInstructor(request.getParameter("Instructor"));
	f.setSubject(request.getParameter("Subject"));
	String result=FeedbackCrud.addFeedBack(f);
	out.println(result);
}


      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
